### PR TITLE
Fix filename_filter check on double click #36

### LINKED ISSUE #36: filename_filter is only checked for buttons, not when double-clicking
The buttons only enable when filename_filter matches the selected file, however when double-clicking and File can be opened.

### PR DESCRIPTION
**Pull request by Fabus1184**
Fixes #36 by extra checking on double click

### CODE REVIEW

File: src/lib.rs [hunk 1]
```diff
@@ -563,13 +564,27 @@ impl FileDialog {
...
+                        command = Some(Command::Open(info.clone()));
+                      }
+                    }
+                    DialogType::SaveFile => {
+                      if info.dir {
+                        command = Some(Command::OpenSelected);
+                      } else if (self.filename_filter)(self.filename_edit.as_str()) {
+                        command = Some(Command::Save(info.clone()));
+                      }
+                    }
```
Comment (Barugon) [inline src/lib.rs:586]: `OpenFile` and `SaveFile` look exactly the same. They could be combined.

```Rust
                    DialogType::OpenFile | DialogType::SaveFile => {
                      // open or save file only if name matches filter
                      if info.dir {
                        command = Some(Command::OpenSelected);
                      } else if (self.filename_filter)(self.filename_edit.as_str()) {
                        command = Some(Command::Open(info.clone()));
                      }
                    }
```

Comment (Fabus1184) [reply src/lib.rs:586]: No, OpenFile does Command::Open and SaveFile does Command::Save

**Review by Barugon — APPROVED** [review]
